import MostLikelyToGame from '@/components/MostLikelyTo';

const CHALLENGES = [
"have a one-night stand and forget their name",
  "hook up with someone way older",
  "hook up with someone way younger",
  "get caught doing something freaky in public",
  "send a risky text and instantly regret it",
  "flirt their way out of a speeding ticket",
  "have the highest body count",
  "get caught sneaking someone in",
  "go home with someone they just met",
  "ghost someone after hooking up",
  "be the loudest in bed",
  "have the weirdest kinks",
  "hook up with their ex again",
  "accidentally send a spicy message to the wrong person",
  "fall for someone completely off-limits",
  "secretly be into something super freaky",
  "try something spicy just to check it off their list",
  "hook up with two people in the same friend group",
  "get caught watching something spicy",
  "make out with multiple people in one night",
  "have a spicy dream about someone unexpected",
  "hook up in a public restroom",
  "kiss someone just to make someone else jealous",
  "have a secret sneaky link",
  "get a tattoo on a dare",
  "hook up with a celebrity if given the chance",
  "accidentally call someone by the wrong name in bed",
  "have a crazy hookup story no one believes",
  "be into something freakier than they admit",
  "forget someone's name right after meeting them",
  "hook up with someone on vacation and never talk again",
  "have a secret crush on a friend’s parent",
  "hook up with a professor or boss",
  "have a forbidden office romance",
  "go on a date just for free food",
  "make the first move in a spicy situation",
  "send spicy texts while sitting next to someone else",
  "have the wildest dating history",
  "get back together with a toxic ex",
  "have a crush on someone way out of their league",
  "fall in love after a one-night stand",
  "flirt with someone they shouldn’t",
  "sneak out to meet someone late at night",
  "be involved in a love triangle",
  "go through someone’s phone out of curiosity",
  "keep a hookup a secret from everyone",
  "pretend to be innocent but is actually the freakiest",
  "have a sneaky link nobody knows about",
  "have a spicy moment at a family event",
  "hook up with an ex’s best friend",
  "get caught in a compromising position",
  "be the best at keeping secrets about hookups",
  "flirt with someone just to get what they want",
  "get hit on the most when going out",
  "make out with a stranger at a party",
  "have a freaky alter ego no one knows about",
  "try something completely wild in the bedroom",
  "have the most game when it comes to flirting",
  "get spicy in the most unexpected place",
  "accidentally send a spicy pic to the wrong person",
  "date two people at the same time without them knowing",
  "lie about their body count",
  "hook up in a risky place",
  "use a fake name during a sneaky situation",
  "secretly be into something really unusual",
  "be the first to get married just for the drama",
  "get caught sneaking out after a hookup",
  "spoil someone just because they’re attracted to them",
  "hook up in an elevator",
  "have a night so wild they barely remember it",
  "use a dating app just for a hookup",
  "try role-playing in the bedroom",
  "leave a party early for a sneaky reason",
  "be the best at keeping a secret affair",
  "have the biggest glow-up after a breakup",
  "date someone just because they’re rich",
  "fall for someone completely unexpected",
  "have the wildest fantasies",
  "hook up with someone they just met online",
  "end up in handcuffs (for a fun reason)",
  "turn down a hookup just to keep their mystery",
  "make the boldest first move",
  "be the best at sneaky links",
  "be the one who always gets dared to do something spicy",
  "hook up in the backseat of a car",
  "flirt their way into VIP at a club",
  "have a secret admirer they don’t know about",
  "go viral for something freaky",
  "have the most interesting stories to tell",
  "be the one to suggest something crazy in bed",
  "have an ex still obsessed with them",
  "text their ex while drunk and regret it",
  "have the most unexpected wild side",
  "hook up with a complete stranger just for the thrill",
  "be the most unpredictable when it comes to dating",
  "flirt with someone they know they shouldn’t",
  "be the first to suggest trying something new in bed",
  "be the best kisser in the group",
  "be the most adventurous when it comes to dating",
  "have the most fun when single",
  "do something wild just to say they did it",
  "make the first move at a party",
  "end up with the hottest partner",
  "be the one with the most unforgettable hookup stories"
];

export default function StarterScreen() {
  return <MostLikelyToGame challenges={CHALLENGES} title="Extreme" />;
} 