import TruthOrDareGame from "@/components/TruthOrDare";

const TRUTHS = [
  "whats the wildest place youve had sex?",
  "have you ever hooked up with a friends ex?",
  "whats your naughtiest fantasy youve never told?",
  "who in this room would you kiss right now?",
  "have you ever sent nudes to the wrong person?",
  "whats the kinkiest thing youve tried?",
  "have you ever faked an orgasm?",
  "whos the last person you sexted?",
  "whats your favorite sex toy?",
  "have you ever hooked up in a car?",
  "whats the most public place youve made out?",
  "have you ever had a one-night stand?",
  "whats the dirtiest text youve sent?",
  "have you ever kissed someone of the same sex?",
  "whats your wildest role-play experience?",
  "have you ever been caught having sex?",
  "whos the hottest person youve slept with?",
  "whats your go-to move to turn someone on?",
  "have you ever used handcuffs in bed?",
  "whats the most daring place youve masturbated?",
  "have you ever hooked up with a coworker?",
  "whats the longest youve gone without sex?",
  "have you ever watched porn with someone else?",
  "whats your favorite body part on a partner?",
  "have you ever had a threesome?",
  "whats the naughtiest thing youve done drunk?",
  "have you ever hooked up outdoors?",
  "whats your secret turn-on no one knows?",
  "have you ever used food during sex?",
  "whos the last person you thought about naked?",
  "whats the most times youve had sex in a day?",
  "have you ever sexted during work?",
  "whats your favorite position and why?",
  "have you ever hooked up with an exs friend?",
  "whats the wildest dare youve done?",
  "have you ever been turned on in public?",
  "whats the dirtiest dream youve had?",
  "have you ever used a blindfold during sex?",
  "whos the oldest person youve slept with?",
  "whats your most embarrassing hookup story?",
  "have you ever kissed someone you just met?",
  "whats the freakiest thing youve done solo?",
  "have you ever hooked up in a bathroom?",
  "whats your favorite thing to wear to bed?",
  "have you ever had a fling on vacation?",
  "whats the hottest text youve received?",
  "have you ever tried bondage?",
  "whos the last person you flirted with?",
  "whats your wildest party hookup story?",
  "have you ever used a sex app?",
  "whats the most adventurous place youve kissed?",
  "have you ever hooked up after a fight?",
  "whats your favorite way to tease someone?",
  "have you ever had sex with music on?",
  "whats the naughtiest thing youve done in a group?",
  "have you ever skinny-dipped with someone?",
  "whats your steamiest shower story?",
  "have you ever hooked up with a stranger?",
  "whats the wildest thing youve worn to impress?",
  "have you ever used dirty talk in bed?",
  "whos the last person you undressed in your mind?",
  "whats your favorite foreplay trick?",
  "have you ever hooked up at a party?",
  "whats the hottest thing a partners done to you?",
  "have you ever tried a sex game?",
  "whats your most spontaneous hookup?",
  "have you ever been turned on by a dare?",
  "whats the freakiest place youve sent a nude from?",
  "have you ever hooked up in a kitchen?",
  "whats your wildest drunk confession?",
  "have you ever used a toy in public?",
  "whos the last person you wanted to kiss?",
  "whats your favorite sexy movie scene?",
  "have you ever had sex in the morning?",
  "whats the dirtiest thing youve whispered?",
  "have you ever hooked up with a friend?",
  "whats your naughtiest vacation memory?",
  "have you ever tried spanking in bed?",
  "whats the hottest thing youve done on a dare?",
  "have you ever sexted someone in this room?",
  "whats your wildest fantasy about someone here?",
  "have you ever hooked up in a pool?",
  "whats the freakiest thing youve googled?",
  "have you ever used ice during intimacy?",
  "whos the last person you checked out?",
  "whats your steamiest late-night story?",
  "have you ever hooked up after dancing?",
  "whats the naughtiest bet youve made?",
  "have you ever tried a risky quickie?",
  "whats your favorite way to flirt?",
  "have you ever hooked up in a living room?",
  "whats the wildest thing youve done sober?",
  "have you ever used a pillow for fun?",
  "whos the hottest stranger youve met?",
  "whats your dirtiest secret crush?",
  "have you ever kissed someone during a game?",
  "whats the freakiest thing youve admitted?",
  "have you ever hooked up after a text?"
  ];
  

  const DARES = [
    "send a flirty text to the last person you messaged",
    "kiss the person to your left on the neck",
    "take off one piece of clothing and leave it off",
    "whisper something dirty in someones ear",
    "do a seductive dance for 30 seconds",
    "text a nude to someone in your contacts",
    "lick whipped cream off someones finger",
    "wear someone elses underwear for the next round",
    "fake an orgasm as loud as you can",
    "blindfold yourself and guess whos touching you",
    "send a suggestive selfie to the group chat",
    "kiss someones bare stomach",
    "run your hands down someones back seductively",
    "sext a random contact for 10 seconds",
    "take a shot off someones body",
    "bite someones earlobe gently",
    "strip down to your underwear for one round",
    "give a lap dance to the person across from you",
    "kiss someone with your hands behind your back",
    "tease someone with an ice cube on their skin",
    "send a dirty voice memo to a crush",
    "wear a blindfold for the next three turns",
    "spoon the person next to you for a minute",
    "flash the group for three seconds",
    "lick someones neck slowly",
    "text I want you to someone youve hooked up with",
    "swap shirts with someone in the room",
    "kiss the person to your right on the lips",
    "rub someones thigh under the table",
    "take a seductive sip from someones drink",
    "send a nude snap with a 5-second timer",
    "grind on someone for 10 seconds",
    "tie someones hands with a scarf for a round",
    "kiss someones inner thigh",
    "post a thirsty story on social media",
    "bite someones lip during a kiss",
    "tease someone with a feather or soft object",
    "call a friend and flirt shamelessly",
    "remove someone elses shirt with your teeth",
    "straddle someone for 15 seconds",
    "send a suggestive wink to everyone in the room",
    "lick chocolate syrup off someones hand",
    "wear socks and nothing else for a round",
    "kiss someone blindfolded",
    "text a dirty joke to your ex",
    "give someone a hickey in plain sight",
    "dance with no music as sexy as possible",
    "use your tongue to trace a heart on someone",
    "take a risky pic in the bathroom right now",
    "moan someones name in the room",
    "swap underwear with someone here",
    "kiss someones collarbone",
    "tease someone with your breath on their neck",
    "send a flirty DM to a stranger online",
    "strip one layer for every wrong answer next round",
    "play with someones hair seductively",
    "kiss someone using only your tongue",
    "text come over to a booty call",
    "run an ice cube down your chest",
    "pose for a spicy group photo",
    "lick someones wrist slowly",
    "wear a partners jacket and nothing else",
    "kiss someone upside down",
    "send a nude with just emojis covering you",
    "grind the air like someones there",
    "bite someones shoulder playfully",
    "tease someone with a piece of candy",
    "call out a dirty fantasy loud",
    "kiss someones lower back",
    "remove your socks with your mouth",
    "text a pickup line to a random number",
    "give a foot massage with flair",
    "dance on someone like a stripper",
    "kiss someone through their shirt",
    "send a spicy meme to the group",
    "trace someones jawline with your finger",
    "wear lipstick and leave a mark on someone",
    "fake a steamy phone call",
    "kiss someones hand like its foreplay",
    "tease someones ear with your voice",
    "strip to music for 20 seconds",
    "lick a spoon seductively",
    "text last night was wild to a friend",
    "kiss someones cheek way too close to their lips",
    "run your fingers through someones hair",
    "pose nude with just a towel for a pic",
    "bite a piece of fruit like its a turn-on",
    "kiss someone with a drink in your mouth",
    "tease someones back with your nails",
    "send a flirty video to the group",
    "strut around the room in your underwear",
    "kiss someones knuckles seductively",
    "text a dirty secret to someone here",
    "grind on a pillow for laughs",
    "lick someones finger like its dessert",
    "wear someones hat and strip a layer",
    "kiss the air like its your lover",
    "tease someone with a slow wink"
    ];
    

export default function StarterScreen() {
  return (
    <TruthOrDareGame
      truths={TRUTHS}
      dares={DARES}
      title="Starter Pack 🎮"
    />
  );
}