import NeverHaveIEverGame from '@/components/NeverHaveIEverGame';

const CHALLENGES = [
"hooked up in a public bathroom",
"sent a risky nude to someone I barely knew",
"had a threesome with people I met that night",
"used handcuffs during a wild hookup",
"kissed someone during a drunken dare",
"had sex in a car parked somewhere sketchy",
"tried a blindfold in the bedroom",
"sexted while at a boring event",
"hooked up with an ex just for old times’ sake",
"used a sex toy with a partner",
"made out in a dark corner at a party",
"had a one-night stand with zero regrets",
"worn something kinky under regular clothes",
"hooked up in someone else’s house",
"tried role-playing with a partner",
"had sex somewhere I could’ve been caught",
"sent a dirty text during work hours",
"kissed someone of the same sex for fun",
"used food in a naughty way",
"had a quickie in an unexpected place",
"hooked up with a friend’s ex",
"watched porn with someone else",
"tried a new kink I’d never heard of before",
"had sex with the lights fully on",
"snuck a hookup into my place late at night",
"used a vibrator in a sneaky situation",
"made out with someone I just met",
"had sex outdoors under the stars",
"worn lingerie or underwear to impress",
"hooked up after a wild night of drinking",
"tried a sex game with rules",
"had a fling with someone older or younger",
"kissed someone in the rain like a movie",
"used a mirror during a steamy moment",
"hooked up in a hotel room",
"sent a nude just to tease",
"had sex with music blasting",
"tried bondage with ropes or ties",
"hooked up with a coworker",
"made a sex tape for personal use",
"had a loud session with thin walls",
"used ice cubes to spice things up",
"hooked up at a friend’s party",
"tried a position I saw online",
"had sex in the shower",
"sexted someone while they were in the same room",
"hooked up with someone I met online",
"worn something sexy to bed",
"had a fling on vacation",
"used dirty talk to turn someone on",
"kissed someone in a crowded place",
"had sex in the morning unexpectedly",
"tried a toy I bought on a whim",
"hooked up after a heated argument",
"made out in a backseat",
"had sex with someone watching nearby",
"used a feather or soft object in bed",
"sent a suggestive pic from a bathroom",
"hooked up with a stranger at a bar",
"tried a kink with spanking",
"had sex during a movie",
"worn a partner’s clothes after a hookup",
"hooked up in a kitchen",
"used a sexy nickname during intimacy",
"had a fling with no strings attached",
"tried phone sex with someone far away",
"kissed someone during a game night",
"had sex in a tent or sleeping bag",
"used lotion or oil for extra fun",
"hooked up after skinny-dipping",
"sent a flirty voice message",
"had sex with curtains wide open",
"tried a lap dance for a partner",
"hooked up in a basement",
"used a scarf or tie as a blindfold",
"had a steamy makeout in a club",
"tried a kink with light biting",
"had sex after a dare",
"worn nothing but a coat to surprise someone",
"hooked up during a storm",
"used a sex toy solo in a bold spot",
"kissed someone in a pool or hot tub",
"had sex after a late-night talk",
"tried a fantasy I’d kept secret",
"hooked up with someone from a dating app",
"used candles for a sensual vibe",
"had sex in a living room",
"sent a nude after a flirty bet",
"hooked up after dancing all night",
"tried a loud toy with a partner",
"had sex in a borrowed car",
"kissed someone during a power outage",
"used a pillow in a creative way",
"hooked up after a flirty text exchange",
"tried a quickie before guests arrived",
"had sex with a playlist I made",
"worn heels or boots to bed",
"hooked up in a bathroom at a party",
"used my hands to tease under a table"
];

export default function ExtremeScreen() {
  return <NeverHaveIEverGame challenges={CHALLENGES} title="Extreme Mode" />;
} 