import NeverHaveIEverGame from '@/components/NeverHaveIEverGame';

const CHALLENGES = [
  "Had a crush on a friend’s partner.",
  "Used a cheesy pick-up line seriously.",
  "Sent a risky text and regretted it.",
  "Had a crush on a teacher or professor.",
  "Kissed more than one person in 24 hours.",
  "Kissed a stranger.",
  "Gone on a blind date.",
  "Had a date so bad I snuck out.",
  "Made the first move on someone.",
  "Flirted with someone to get free stuff.",
  "Lied about my relationship status.",
  "Hooked up with someone just to make someone else jealous.",
  "Gotten back with an ex.",
  "Snooped through my partner’s phone.",
  "Ghosted someone after a date.",
  "Faked being into someone just to avoid hurting their feelings.",
  "Been caught in a lie by a partner.",
  "Given someone a fake number.",
  "Pretended to be single when I wasn’t.",
  "Had a secret relationship.",
  "Had a one-night stand.",
  "Made out in a bar.",
  "Gotten too drunk and confessed something embarrassing.",
  "Woken up next to someone and didn’t remember their name.",
  "Taken a drunk dare and regretted it.",
  "Danced on a bar or table.",
  "Blacked out and had to be told what happened.",
  "Lost an item of clothing on a wild night out.",
  "Been carried out of a party.",
  "Flirted with a bartender for free drinks.",
  "Kissed someone from a dating app.",
  "Made out with a coworker.",
  "Gone home with someone I just met.",
  "Hooked up with a roommate.",
  "Hooked up with an ex’s best friend.",
  "Had a crush on a best friend.",
  "Had a 'situationship'.",
  "Hooked up with someone just for the thrill.",
  "Kissed someone at work.",
  "Lied about my body count.",
  "Sent a flirty DM to a celeb or influencer.",
  "Kissed someone and instantly regretted it.",
  "Done something spicy in a car.",
  "Had a hookup interrupted by someone.",
  "Tried role-playing.",
  "Had a crush on an authority figure.",
  "Had a crush on a friend’s sibling.",
  "Done something spicy in a public place.",
  "Sent a message I wish I could unsend.",
  "Had a dream about someone I shouldn’t have.",
  "Kissed someone else while in a relationship.",
  "Been tempted to cheat.",
  "Had feelings for two people at once.",
  "Hidden a relationship from my friends.",
  "Suspected I was being cheated on.",
  "Had an ex try to win me back.",
  "Fallen for someone I shouldn’t have.",
  "Gone through a partner’s DMs.",
  "Broken up with someone for someone else.",
  "Been caught sneaking around.",
  "Gone skinny dipping.",
  "Sent a risky text to the wrong person.",
  "Had a forbidden crush.",
  "Gone on a trip just to see someone.",
  "Flirted with someone way out of my league.",
  "Tried speed dating.",
  "Made the first move on a crush.",
  "Been in a love triangle.",
  "Had a secret admirer.",
  "Had an accidental wardrobe malfunction.",
  "Stalked an ex online.",
  "Subtweeted about an ex.",
  "Sent a flirty Snapchat.",
  "Posted something just to make someone jealous.",
  "Re-read old messages from an ex.",
  "Deleted a message before the other person saw it.",
  "Catfished or pretended to be someone else online.",
  "Created a fake account to check on someone.",
  "Screenshotted a private convo for my friends.",
  "Liked an old post by accident while stalking someone.",
  "Fallen in love too fast.",
  "Said 'I love you' first.",
  "Been in a long-distance relationship.",
  "Cried over a crush.",
  "Written a love letter or poem.",
  "Gotten matching outfits with a partner.",
  "Had a song that reminded me of an ex.",
  "Stayed friends with an ex.",
  "Regretted breaking up with someone.",
  "Accidentally texted the wrong person something flirty.",
  "Walked in on someone in an awkward situation.",
  "Been caught in an awkward position.",
  "Had a date end in complete disaster.",
  "Used someone’s toothbrush without them knowing.",
  "Slipped and fallen in front of someone attractive.",
  "Had my parents walk in on something embarrassing.",
  "Had a crush on a celebrity way older than me.",
  "Accidentally said something too personal on a first date.",
  "Laughed so hard I snorted on a date."
];

export default function SpicyScreen() {
  return <NeverHaveIEverGame challenges={CHALLENGES} title="Spicy Edition" />;
} 