import NeverHaveIEverGame from '@/components/NeverHaveIEverGame';

const CHALLENGES = [
  "sent a text to the wrong person 📱",
  "fallen asleep in class 😴", 
  "pretended to be sick to skip work/school 🤒",
  "eaten food that fell on the floor 😋",
  "stalked someone on social media 👀",
  "lied about my age 🎂",
  "forgotten someone's name while talking to them 😅",
  "sang karaoke in public 🎤",
  "accidentally liked an old post while stalking 🙈",
  "pulled an all-nighter 🌙",
  "forgotten my password right after changing it 🔑",
  "walked into a glass door 🚪",
  "sent a message to the wrong group chat 💬",
  "worn clothes inside out in public 👕",
  "tried to unlock the wrong car 🚗",
  "gotten stuck in an elevator ⬆️",
  "pretended to know a song's lyrics 🎵",
  "waved at someone who wasn't waving at me 👋",
  "taken a selfie in public and felt awkward 📸",
  "accidentally called someone while my phone was in my pocket 📞",
  "eaten an entire pizza by myself 🍕",
  "binged an entire TV series in one day 📺",
  "forgotten where I parked my car 🅿️",
  "tried to push a pull door 🚪",
  "lost my phone while it was in my hand 📱",
  "talked to myself in public 🗣️",
  "tripped over nothing 🦶",
  "gotten brain freeze from eating too fast 🧊",
  "laughed at a joke I didn't understand 😂",
  "pretended to be on the phone to avoid someone 📱",
  "gone to work/school with different shoes on 👞",
  "fallen asleep during a movie at the cinema 🎬",
  "accidentally liked a really old Instagram post 📱",
  "gotten lost following GPS directions 🗺️",
  "danced in an elevator when I thought I was alone 💃",
  "replied all to an email by mistake 📧",
  "walked into a room and forgotten why I went there 🚶",
  "taken a picture of my food for social media 📸",
  "used the wrong emoji in a serious conversation 😬",
  "gotten competitive over a board game 🎲",
  "pretended to understand what someone said 👂",
  "spent an entire day in pajamas 🛋️",
  "forgotten my own birthday for a moment 🎂",
  "tried to scroll on a paper book 📚",
  "said 'you too' when a waiter said 'enjoy your meal' 🍽️",
  "posted something online and immediately deleted it 🙈",
  "forgotten my phone was on speaker in public 📢",
  "tried to drink from an empty cup ☕",
  "walked around with something stuck in my teeth 😬",
  "gotten into the wrong car thinking it was my ride 🚗",
  "accidentally opened my front camera in public 📸",
  "forgotten to unmute myself in a video call 🎤",
  "put an empty container back in the fridge 🌭",
  "used a filter during a work video call 👾",
  "double-dipped a chip when no one was looking 🌯",
  "pretended to know about a movie I've never seen 🎬",
  "gotten locked out of my house 🏠",
  "sent a screenshot to the person I was screenshotting 😱",
  "tried to unlock my house with my car keys 🔑",
  "forgotten someone's name during introductions 🤝",
  "watched the same show twice without realizing 📺",
  "worn clothes inside out all day 👕",
  "accidentally liked an ex's post 💔",
  "fallen asleep during a video call 😴",
  "pretended to laugh at a joke I didn't hear 😂",
  "taken a bite of something too hot 🔥",
  "walked into a pole while looking at my phone 📱",
  "forgotten my age for a moment 🎂",
  "used the wrong name for my teacher/boss 😅",
  "accidentally called someone 'mom' or 'dad' 👪",
  "gotten stuck in a sweater while trying it on 👕",
  "dropped my phone on my face while lying down 📱",
  "said 'bye' and walked in the same direction 👋",
  "tried to drink from a closed water bottle 💧",
  "lost rock paper scissors more than 5 times in a row ✌️",
  "forgotten my PIN at the ATM 💳",
  "sent a voice message and immediately regretted it 🎤",
  "tried to use an expired coupon 🏷️",
  "gotten into an argument with a GPS 🗺️",
  "forgotten what day of the week it was 📅",
  "used shampoo twice and skipped conditioner 🧴",
  "eaten dessert before dinner 🍰",
  "pretended to know about sports 🏈",
  "bought something just for the free shipping 📦",
  "forgotten my umbrella on a rainy day ☔",
  "tried to charge a dead device with a turned-off power strip 🔌",
  "gotten caught singing in the car by other drivers 🎵",
  "used the wrong emoji to react to sad news 😬",
  "forgotten to save a document and lost everything 💾",
  "tried to open my house with my office keycard 🔑",
  "put something in a 'safe place' and lost it 🤔",
  "gotten caught taking a selfie 📸",
  "spelled my own name wrong ✍️",
  "forgotten what I was saying mid-sentence 💭",
  "tried to tap a photo in a physical magazine 📱",
  "gotten caught in a reply-all email chain 📧",
  "forgotten to add water to my instant noodles 🍜",
  "worn mismatched socks all day 🧦",
  "tried to turn up the volume on a picture 🔊",
  "accidentally started a video call 📹",
];

export default function StarterScreen() {
  return <NeverHaveIEverGame challenges={CHALLENGES} title="Starter Pack" />;
} 